terms:
  - id: Chicago Theological Seminary
    term: Chicago Theological Seminary
    active: true
  - id: Oblate School of Theology
    term: Oblate School of Theology
    active: true
  - id: Atla
    term: Atla
    active: true
