default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  image_uploadtab: true
  toolbar1: styleselect | bold italic underline | link hr | undo redo | image | fontsizeselect | code
  toolbar2: indent outdent | alignleft aligncenter alignright | table | numlist bullist | fullscreen
  plugins:
    - table
    - fullscreen
    - lists
    - link
    - autolink
    - image
    - code
custom:
  <<: *default
